import { z } from 'zod';

/** A region of interest in the source image */
export const RegionSchema = z.object({
  id: z.string(),
  label: z.string(),
  description: z.string(),
  /** Bounding box as percentage of image dimensions (0-100) */
  bbox: z.object({
    x: z.number().min(0).max(100),
    y: z.number().min(0).max(100),
    width: z.number().min(0).max(100),
    height: z.number().min(0).max(100),
  }),
});

/** A single scene beat in the narrative */
export const SceneBeatSchema = z.object({
  /** Which region to focus on (or "overview" for the full painting) */
  regionId: z.string(),
  /** Narration text displayed during this beat */
  narration: z.string(),
  /** Duration in seconds */
  durationSeconds: z.number().min(1).max(15),
  /** Zoom level (1 = fit, 2 = 2x zoom, etc.) */
  zoom: z.number().min(0.8).max(5),
  /** Transition type: "pan" smoothly moves camera, "cut" clips region to full screen */
  transition: z.enum(['pan', 'cut']).default('pan'),
  /** Mood tag for SFX/meme selection */
  mood: z.enum(['dramatic', 'mysterious', 'humorous', 'reverent', 'tense', 'peaceful', 'epic']),
  /** Optional sound effect key */
  sfx: z.string().optional(),
  /** Optional meme overlay key */
  meme: z.string().optional(),
});

/** The complete scene manifest generated by the workflow */
export const SceneManifestSchema = z.object({
  /** Title of the painting */
  title: z.string(),
  /** Artist name */
  artist: z.string(),
  /** Year or period */
  year: z.string(),
  /** Path to the source image */
  imagePath: z.string(),
  /** Image dimensions in pixels */
  imageWidth: z.number(),
  imageHeight: z.number(),
  /** Detected regions of interest */
  regions: z.array(RegionSchema),
  /** Ordered sequence of scene beats */
  beats: z.array(SceneBeatSchema),
  /** Total video duration in seconds */
  totalDurationSeconds: z.number(),
});

export type Region = z.infer<typeof RegionSchema>;
export type SceneBeat = z.infer<typeof SceneBeatSchema>;
export type SceneManifest = z.infer<typeof SceneManifestSchema>;
